import { Bot, Cpu, Database, Glasses, HardDrive, KeyRound, Network, RadioTower, ShieldCheck, UserRound } from "lucide-react";
import { PageHeader } from "@/components/layout/PageHeader";
import { Card, CardBody, CardHeader } from "@/components/ui/card";
import { Segmented } from "@/components/ui/segmented";
import { StatusPill } from "@/components/ui/status-pill";
import { useMeta } from "@/lib/queries";
import { useUi } from "@/lib/store";

const ROADMAP = [
  {
    icon: Network,
    title: "Federated learning across bases",
    body: "Each base trains on its own health-monitoring data and shares only model weights; a central aggregator improves the fleet model without moving raw data off-site.",
  },
  {
    icon: RadioTower,
    title: "Edge gateway in hangars",
    body: "A ruggedised gateway ingests HUMS downloads and IoT sensors at the flight line, scores RUL locally and syncs when the network is available.",
  },
  {
    icon: Glasses,
    title: "AR maintenance guidance",
    body: "Step-by-step overlays for the recommended checks on a tablet or headset, linked to the Copilot answer and the part's QR history.",
  },
];

export default function SettingsPage() {
  const { data: meta } = useMeta();
  const { theme, setTheme, density, setDensity } = useUi();
  const rows = [
    { icon: HardDrive, label: "Deployment", value: meta?.deployment ?? "on-premise / offline", tone: "ready" as const, note: "Runs fully offline after setup: bundled fonts, offline map, local models and database." },
    { icon: Database, label: "Data residency", value: "Local SQLite (Postgres-compatible)", tone: "ready" as const, note: "No data leaves the deployment; no telemetry or analytics calls." },
    { icon: ShieldCheck, label: "Audit", value: "Enabled · SHA-256 hash chain", tone: "ready" as const, note: "Records, schedule changes and approvals are chained and verifiable." },
    { icon: KeyRound, label: "Access control", value: "Role-based, enforced on the API", tone: "ready" as const, note: "Five roles; every endpoint checks the caller's role." },
    {
      icon: Bot,
      label: "Copilot language model",
      value: meta?.llm_enabled ? "Claude via API key (optional)" : "Offline retrieval mode",
      tone: meta?.llm_enabled ? ("info" as const) : ("ready" as const),
      note: meta?.llm_enabled ? "Answers are generated by Claude from local sources; retrieval-only fallback if unreachable." : "Set ANTHROPIC_API_KEY to enable generated answers; retrieval-only answers work without it.",
    },
    { icon: Cpu, label: "Engine data", value: meta?.engine_data_source ?? "—", tone: "info" as const, note: "Fleet data is simulated; engine degradation trajectories come from the dataset shown." },
  ];
  return (
    <>
      <PageHeader title="Settings" description="Deployment, security posture, preferences and roadmap." />
      <div className="grid gap-4 xl:grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)]">
        <Card>
          <CardHeader title="Deployment & security" />
          <ul className="divide-y divide-border">
            {rows.map((r) => (
              <li key={r.label} className="flex items-start gap-3 px-4 py-3">
                <r.icon size={17} strokeWidth={1.75} className="mt-0.5 shrink-0 text-subtle" aria-hidden />
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <p className="text-sm text-strong">{r.label}</p>
                    <StatusPill tone={r.tone} label={r.value} />
                  </div>
                  <p className="mt-0.5 text-xs text-subtle">{r.note}</p>
                </div>
              </li>
            ))}
          </ul>
        </Card>
        <div className="space-y-4">
          <Card>
            <CardHeader title="Preferences" subtitle="Stored on this device" />
            <CardBody className="space-y-4 text-sm">
              <div className="flex items-center justify-between gap-3">
                <span className="text-body">Theme</span>
                <Segmented ariaLabel="Theme" value={theme} onChange={setTheme} options={[{ value: "dark", label: "Dark" }, { value: "light", label: "Light" }]} />
              </div>
              <div className="flex items-center justify-between gap-3">
                <span className="text-body">Table density</span>
                <Segmented ariaLabel="Density" value={density} onChange={setDensity} options={[{ value: "comfortable", label: "Comfortable" }, { value: "compact", label: "Compact" }]} />
              </div>
              <div className="flex items-center justify-between gap-3">
                <span className="text-body">Signed in as</span>
                <span className="flex items-center gap-1.5 text-strong">
                  <UserRound size={14} strokeWidth={1.75} className="text-subtle" /> {meta?.role.user} · {meta?.role.label}
                </span>
              </div>
            </CardBody>
          </Card>
          <Card>
            <CardHeader title="Keyboard shortcuts" />
            <CardBody>
              <dl className="grid grid-cols-2 gap-x-4 gap-y-2 text-sm">
                {[
                  ["⌘K / Ctrl K", "Command palette"],
                  ["/", "Search"],
                  ["g o", "Overview"],
                  ["g f", "Fleet"],
                  ["g p", "Planner"],
                  ["g h", "Predictive Health"],
                  ["g c", "Copilot"],
                  ["t", "Toggle theme"],
                ].map(([k, v]) => (
                  <div key={k} className="contents">
                    <dt>
                      <kbd className="rounded border border-border px-1.5 py-0.5 font-mono text-xs text-body">{k}</kbd>
                    </dt>
                    <dd className="text-subtle">{v}</dd>
                  </div>
                ))}
              </dl>
            </CardBody>
          </Card>
        </div>
      </div>
      <Card className="mt-4">
        <CardHeader title="About · Phase-2 roadmap" subtitle="AeroPulse for SIH26249 — Air Power: Predictive Maintenance & Fleet Availability" />
        <div className="grid gap-px bg-border md:grid-cols-3">
          {ROADMAP.map((r) => (
            <div key={r.title} className="bg-surface p-4">
              <div className="flex items-center justify-between">
                <r.icon size={18} strokeWidth={1.75} className="text-accent" aria-hidden />
                <StatusPill tone="neutral" label="Planned" />
              </div>
              <p className="mt-3 font-medium text-strong">{r.title}</p>
              <p className="mt-1 text-sm text-subtle">{r.body}</p>
            </div>
          ))}
        </div>
      </Card>
    </>
  );
}
